### ISSUE TITLE
Create Routing

### ISSUE THREAD

**Issue by nicksessa** [nicksessa/Pied-Piper-II#3]
I started doing this using both the MVC template and Pryesh's example.

**Comment by srkyaganti** [comment]
Hi,

Can I contribute to this?

**Comment by nicksessa** [comment]
> Hi,
> 
> Can I contribute to this?

Hi Srikar! Thanks for offering but this is a closed project.

Best Regards,
Nick

**Comment by nicksessa** [comment]
The routing is setup, but needs to be modified to reflect the additional calls to the db.  closing this issue and will address the other issues as they come up.
